CREATE TABLE class (
  class_id INTEGER,
  name VARCHAR(100),
  type VARCHAR(255),
  alignment VARCHAR(255),
  hit_die VARCHAR(255),
  class_skills VARCHAR,
  skill_points VARCHAR(255),
  skill_points_ability VARCHAR(255),
  spell_stat VARCHAR(255),
  proficiencies VARCHAR(255),
  spell_type VARCHAR(255),
  race VARCHAR(255),
  weapon_proficiency VARCHAR(255),
  base_attack_bonus VARCHAR(255),
  skill VARCHAR(255),
  feat VARCHAR(255),
  spells VARCHAR(255),
  req_languages VARCHAR(255),
  psionics VARCHAR(255),
  special VARCHAR(255),
  class_spells VARCHAR(255),
)

CREATE TABLE spell (
  spell_id INTEGER,
  name VARCHAR(100),
  descriptor VARCHAR(255),
  level VARCHAR(255),
  components VARCHAR,
  casting_time VARCHAR(255),
  range VARCHAR(255),
  target VARCHAR(255),
  area VARCHAR(255),
  effect VARCHAR(255),
  duration VARCHAR(255),
  saving_throw VARCHAR(255),
  spell_resistance VARCHAR(255),
  description VARCHAR(255),
  material_components VARCHAR(255),
  focus VARCHAR(255),
  description VARCHAR(255),
  xp_cost VARCHAR(255),
  verbal_components VARCHAR(255),
 
)
